spring:
  application:
#    name: stock-service
    name: STOCK-SERV
server:
  port: 8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    hostname: localhost